AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'bundle/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'bin/**/*'
    - 'config/deploy.rb'

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - spec/**/*
Metrics/BlockLength:
  Max: 26
  Exclude:
    - spec/**/*
    - config/environments/*