default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pintoo_dev

test:
  <<: *default
  database: pintoo_test

production:
  <<: *default
  database: pintoo
